name: CI
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    # Название job вы можете назвать как угодно
    tests_job:
      # Операционная система в виртуальной машине, в которой запускаются процессы
      runs-on: ubuntu-latest
        # Шаги
        steps:
          # Actions от github: проверяет репозиторий, гит и т.д.
          - uses: actions/checkout@v3

          # Пример однолинейного простого скрипта shell
          - name: Run unit test
            run: python -m unittest discover -v,
