name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run unit tests on Ubuntu
        run: python -m unittest discover -v

  tests_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run unit tests on Windows
        run: python -m unittest discover -v
